# Strict analysis options for Flutter
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_return: error
    missing_required_param: error
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Error prevention
    avoid_print: true
    avoid_empty_else: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    cancel_subscriptions: true
    close_sinks: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    throw_in_finally: true
    unnecessary_statements: true

    # Style
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    prefer_single_quotes: true
    sort_constructors_first: false  # Disabled - purely stylistic, current ordering is fine
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    unnecessary_parenthesis: true
    use_string_buffers: true

    # Documentation (optional - enable if you want)
    # public_member_api_docs: true
