#!/bin/bash
# Generate version.dart with git info
# - If HEAD is tagged: use tag name (e.g., v1.2.3)
# - Otherwise: use short commit hash (e.g., abc1234)

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT_FILE="$PROJECT_DIR/lib/generated/version.dart"

# Get git info
COMMIT_HASH=$(git -C "$PROJECT_DIR" rev-parse --short HEAD 2>/dev/null || echo "unknown")
TAG=$(git -C "$PROJECT_DIR" describe --tags --exact-match HEAD 2>/dev/null || echo "")

# Determine version string and release status
if [ -n "$TAG" ]; then
    VERSION="$TAG"
    IS_RELEASE="true"
else
    VERSION="$COMMIT_HASH"
    IS_RELEASE="false"
fi

# Generate the Dart file
mkdir -p "$(dirname "$OUTPUT_FILE")"
cat > "$OUTPUT_FILE" << EOF
// GENERATED FILE - DO NOT EDIT
// Generated by scripts/generate_version.sh

/// App version information from git.
class AppVersion {
  /// Version string: tag name for releases, commit hash for dev builds.
  static const String version = '$VERSION';

  /// True if built from a tagged release.
  static const bool isRelease = $IS_RELEASE;
}
EOF

echo "Generated $OUTPUT_FILE: version=$VERSION, isRelease=$IS_RELEASE"
